import XCTest
@testable import SQLiteTests

XCTMain([
testCase([
    ("test_distinct_prependsExpressionsWithDistinctKeyword()", AggregateFunctionsTests.test_distinct_prependsExpressionsWithDistinctKeyword),
    ("test_count_wrapsOptionalExpressionsWithCountFunction()", AggregateFunctionsTests.test_count_wrapsOptionalExpressionsWithCountFunction),
    ("test_max_wrapsComparableExpressionsWithMaxFunction()", AggregateFunctionsTests.test_max_wrapsComparableExpressionsWithMaxFunction),
    ("test_min_wrapsComparableExpressionsWithMinFunction()", AggregateFunctionsTests.test_min_wrapsComparableExpressionsWithMinFunction),
    ("test_average_wrapsNumericExpressionsWithAvgFunction()", AggregateFunctionsTests.test_average_wrapsNumericExpressionsWithAvgFunction),
    ("test_sum_wrapsNumericExpressionsWithSumFunction()", AggregateFunctionsTests.test_sum_wrapsNumericExpressionsWithSumFunction),
    ("test_total_wrapsNumericExpressionsWithTotalFunction()", AggregateFunctionsTests.test_total_wrapsNumericExpressionsWithTotalFunction),
    ("test_count_withStar_wrapsStarWithCountFunction()", AggregateFunctionsTests.test_count_withStar_wrapsStarWithCountFunction)
]),
testCase([
    ("test_init_withInMemory_returnsInMemoryConnection()", ConnectionTests.test_init_withInMemory_returnsInMemoryConnection),
    ("test_init_returnsInMemoryByDefault()", ConnectionTests.test_init_returnsInMemoryByDefault),
    ("test_init_withTemporary_returnsTemporaryConnection()", ConnectionTests.test_init_withTemporary_returnsTemporaryConnection),
    ("test_init_withURI_returnsURIConnection()", ConnectionTests.test_init_withURI_returnsURIConnection),
    ("test_init_withString_returnsURIConnection()", ConnectionTests.test_init_withString_returnsURIConnection),
    ("test_readonly_returnsFalseOnReadWriteConnections()", ConnectionTests.test_readonly_returnsFalseOnReadWriteConnections),
    ("test_readonly_returnsTrueOnReadOnlyConnections()", ConnectionTests.test_readonly_returnsTrueOnReadOnlyConnections),
    ("test_changes_returnsZeroOnNewConnections()", ConnectionTests.test_changes_returnsZeroOnNewConnections),
    ("test_lastInsertRowid_returnsLastIdAfterInserts()", ConnectionTests.test_lastInsertRowid_returnsLastIdAfterInserts),
    ("test_lastInsertRowid_doesNotResetAfterError()", ConnectionTests.test_lastInsertRowid_doesNotResetAfterError),
    ("test_changes_returnsNumberOfChanges()", ConnectionTests.test_changes_returnsNumberOfChanges),
    ("test_totalChanges_returnsTotalNumberOfChanges()", ConnectionTests.test_totalChanges_returnsTotalNumberOfChanges),
    ("test_prepare_preparesAndReturnsStatements()", ConnectionTests.test_prepare_preparesAndReturnsStatements),
    ("test_run_preparesRunsAndReturnsStatements()", ConnectionTests.test_run_preparesRunsAndReturnsStatements),
    ("test_scalar_preparesRunsAndReturnsScalarValues()", ConnectionTests.test_scalar_preparesRunsAndReturnsScalarValues),
    ("test_execute_comment()", ConnectionTests.test_execute_comment),
    ("test_transaction_executesBeginDeferred()", ConnectionTests.test_transaction_executesBeginDeferred),
    ("test_transaction_executesBeginImmediate()", ConnectionTests.test_transaction_executesBeginImmediate),
    ("test_transaction_executesBeginExclusive()", ConnectionTests.test_transaction_executesBeginExclusive),
    ("test_transaction_beginsAndCommitsTransactions()", ConnectionTests.test_transaction_beginsAndCommitsTransactions),
    ("test_transaction_beginsAndRollsTransactionsBack()", ConnectionTests.test_transaction_beginsAndRollsTransactionsBack),
    ("test_savepoint_beginsAndCommitsSavepoints()", ConnectionTests.test_savepoint_beginsAndCommitsSavepoints),
    ("test_savepoint_beginsAndRollsSavepointsBack()", ConnectionTests.test_savepoint_beginsAndRollsSavepointsBack),
    ("test_updateHook_setsUpdateHook_withInsert()", ConnectionTests.test_updateHook_setsUpdateHook_withInsert),
    ("test_updateHook_setsUpdateHook_withUpdate()", ConnectionTests.test_updateHook_setsUpdateHook_withUpdate),
    ("test_updateHook_setsUpdateHook_withDelete()", ConnectionTests.test_updateHook_setsUpdateHook_withDelete),
    ("test_commitHook_setsCommitHook()", ConnectionTests.test_commitHook_setsCommitHook),
    ("test_rollbackHook_setsRollbackHook()", ConnectionTests.test_rollbackHook_setsRollbackHook),
    ("test_commitHook_withRollback_rollsBack()", ConnectionTests.test_commitHook_withRollback_rollsBack),
    ("test_createFunction_withArrayArguments()", ConnectionTests.test_createFunction_withArrayArguments),
    ("test_createFunction_createsQuotableFunction()", ConnectionTests.test_createFunction_createsQuotableFunction),
    ("test_createCollation_createsCollation()", ConnectionTests.test_createCollation_createsCollation),
    ("test_createCollation_createsQuotableCollation()", ConnectionTests.test_createCollation_createsQuotableCollation),
    ("test_interrupt_interruptsLongRunningQuery()", ConnectionTests.test_interrupt_interruptsLongRunningQuery)
]),
testCase([
    ("test_create_onVirtualTable_withRTree_createVirtualTableExpression()", RTreeTests.test_create_onVirtualTable_withRTree_createVirtualTableExpression)
]),
testCase([
    ("test_select()", QueryIntegrationTests.test_select),
    ("test_scalar()", QueryIntegrationTests.test_scalar),
    ("test_pluck()", QueryIntegrationTests.test_pluck),
    ("test_insert()", QueryIntegrationTests.test_insert),
    ("test_update()", QueryIntegrationTests.test_update),
    ("test_delete()", QueryIntegrationTests.test_delete)
]),
testCase([
    ("test_drop_compilesDropTableExpression()", SchemaTests.test_drop_compilesDropTableExpression),
    ("test_drop_compilesDropVirtualTableExpression()", SchemaTests.test_drop_compilesDropVirtualTableExpression),
    ("test_drop_compilesDropViewExpression()", SchemaTests.test_drop_compilesDropViewExpression),
    ("test_create_withBuilder_compilesCreateTableExpression()", SchemaTests.test_create_withBuilder_compilesCreateTableExpression),
    ("test_create_withQuery_compilesCreateTableExpression()", SchemaTests.test_create_withQuery_compilesCreateTableExpression),
    ("test_column_compilesColumnDefinitionExpression()", SchemaTests.test_column_compilesColumnDefinitionExpression),
    ("test_column_withIntegerExpression_compilesPrimaryKeyAutoincrementColumnDefinitionExpression()", SchemaTests.test_column_withIntegerExpression_compilesPrimaryKeyAutoincrementColumnDefinitionExpression),
    ("test_column_withIntegerExpression_compilesReferentialColumnDefinitionExpression()", SchemaTests.test_column_withIntegerExpression_compilesReferentialColumnDefinitionExpression),
    ("test_column_withStringExpression_compilesCollatedColumnDefinitionExpression()", SchemaTests.test_column_withStringExpression_compilesCollatedColumnDefinitionExpression),
    ("test_primaryKey_compilesPrimaryKeyExpression()", SchemaTests.test_primaryKey_compilesPrimaryKeyExpression),
    ("test_unique_compilesUniqueExpression()", SchemaTests.test_unique_compilesUniqueExpression),
    ("test_check_compilesCheckExpression()", SchemaTests.test_check_compilesCheckExpression),
    ("test_foreignKey_compilesForeignKeyExpression()", SchemaTests.test_foreignKey_compilesForeignKeyExpression),
    ("test_addColumn_compilesAlterTableExpression()", SchemaTests.test_addColumn_compilesAlterTableExpression),
    ("test_addColumn_withIntegerExpression_compilesReferentialAlterTableExpression()", SchemaTests.test_addColumn_withIntegerExpression_compilesReferentialAlterTableExpression),
    ("test_addColumn_withStringExpression_compilesCollatedAlterTableExpression()", SchemaTests.test_addColumn_withStringExpression_compilesCollatedAlterTableExpression),
    ("test_rename_compilesAlterTableRenameToExpression()", SchemaTests.test_rename_compilesAlterTableRenameToExpression),
    ("test_createIndex_compilesCreateIndexExpression()", SchemaTests.test_createIndex_compilesCreateIndexExpression),
    ("test_dropIndex_compilesCreateIndexExpression()", SchemaTests.test_dropIndex_compilesCreateIndexExpression),
    ("test_create_onView_compilesCreateViewExpression()", SchemaTests.test_create_onView_compilesCreateViewExpression),
    ("test_create_onVirtualTable_compilesCreateVirtualTableExpression()", SchemaTests.test_create_onVirtualTable_compilesCreateVirtualTableExpression),
    ("test_rename_onVirtualTable_compilesAlterTableRenameToExpression()", SchemaTests.test_rename_onVirtualTable_compilesAlterTableRenameToExpression)
]),
testCase([
    ("test_stringExpressionPlusStringExpression_buildsConcatenatingStringExpression()", OperatorsTests.test_stringExpressionPlusStringExpression_buildsConcatenatingStringExpression),
    ("test_numberExpression_plusNumberExpression_buildsAdditiveNumberExpression()", OperatorsTests.test_numberExpression_plusNumberExpression_buildsAdditiveNumberExpression),
    ("test_numberExpression_minusNumberExpression_buildsSubtractiveNumberExpression()", OperatorsTests.test_numberExpression_minusNumberExpression_buildsSubtractiveNumberExpression),
    ("test_numberExpression_timesNumberExpression_buildsMultiplicativeNumberExpression()", OperatorsTests.test_numberExpression_timesNumberExpression_buildsMultiplicativeNumberExpression),
    ("test_numberExpression_dividedByNumberExpression_buildsDivisiveNumberExpression()", OperatorsTests.test_numberExpression_dividedByNumberExpression_buildsDivisiveNumberExpression),
    ("test_numberExpression_prefixedWithMinus_buildsInvertedNumberExpression()", OperatorsTests.test_numberExpression_prefixedWithMinus_buildsInvertedNumberExpression),
    ("test_integerExpression_moduloIntegerExpression_buildsModuloIntegerExpression()", OperatorsTests.test_integerExpression_moduloIntegerExpression_buildsModuloIntegerExpression),
    ("test_integerExpression_bitShiftLeftIntegerExpression_buildsLeftShiftedIntegerExpression()", OperatorsTests.test_integerExpression_bitShiftLeftIntegerExpression_buildsLeftShiftedIntegerExpression),
    ("test_integerExpression_bitShiftRightIntegerExpression_buildsRightShiftedIntegerExpression()", OperatorsTests.test_integerExpression_bitShiftRightIntegerExpression_buildsRightShiftedIntegerExpression),
    ("test_integerExpression_bitwiseAndIntegerExpression_buildsAndedIntegerExpression()", OperatorsTests.test_integerExpression_bitwiseAndIntegerExpression_buildsAndedIntegerExpression),
    ("test_integerExpression_bitwiseOrIntegerExpression_buildsOredIntegerExpression()", OperatorsTests.test_integerExpression_bitwiseOrIntegerExpression_buildsOredIntegerExpression),
    ("test_integerExpression_bitwiseExclusiveOrIntegerExpression_buildsOredIntegerExpression()", OperatorsTests.test_integerExpression_bitwiseExclusiveOrIntegerExpression_buildsOredIntegerExpression),
    ("test_bitwiseNot_integerExpression_buildsComplementIntegerExpression()", OperatorsTests.test_bitwiseNot_integerExpression_buildsComplementIntegerExpression),
    ("test_equalityOperator_withEquatableExpressions_buildsBooleanExpression()", OperatorsTests.test_equalityOperator_withEquatableExpressions_buildsBooleanExpression),
    ("test_inequalityOperator_withEquatableExpressions_buildsBooleanExpression()", OperatorsTests.test_inequalityOperator_withEquatableExpressions_buildsBooleanExpression),
    ("test_greaterThanOperator_withComparableExpressions_buildsBooleanExpression()", OperatorsTests.test_greaterThanOperator_withComparableExpressions_buildsBooleanExpression),
    ("test_greaterThanOrEqualToOperator_withComparableExpressions_buildsBooleanExpression()", OperatorsTests.test_greaterThanOrEqualToOperator_withComparableExpressions_buildsBooleanExpression),
    ("test_lessThanOperator_withComparableExpressions_buildsBooleanExpression()", OperatorsTests.test_lessThanOperator_withComparableExpressions_buildsBooleanExpression),
    ("test_lessThanOrEqualToOperator_withComparableExpressions_buildsBooleanExpression()", OperatorsTests.test_lessThanOrEqualToOperator_withComparableExpressions_buildsBooleanExpression),
    ("test_patternMatchingOperator_withComparableCountableClosedRange_buildsBetweenBooleanExpression()", OperatorsTests.test_patternMatchingOperator_withComparableCountableClosedRange_buildsBetweenBooleanExpression),
    ("test_patternMatchingOperator_withComparableClosedRange_buildsBetweenBooleanExpression()", OperatorsTests.test_patternMatchingOperator_withComparableClosedRange_buildsBetweenBooleanExpression),
    ("test_patternMatchingOperator_withomparableClosedRangeString_buildsBetweenBooleanExpression()", OperatorsTests.test_patternMatchingOperator_withomparableClosedRangeString_buildsBetweenBooleanExpression),
    ("test_doubleAndOperator_withBooleanExpressions_buildsCompoundExpression()", OperatorsTests.test_doubleAndOperator_withBooleanExpressions_buildsCompoundExpression),
    ("test_doubleOrOperator_withBooleanExpressions_buildsCompoundExpression()", OperatorsTests.test_doubleOrOperator_withBooleanExpressions_buildsCompoundExpression),
    ("test_unaryNotOperator_withBooleanExpressions_buildsNotExpression()", OperatorsTests.test_unaryNotOperator_withBooleanExpressions_buildsNotExpression),
    ("test_precedencePreserved()", OperatorsTests.test_precedencePreserved)
]),
testCase([
    ("test_toHex()", BlobTests.test_toHex),
    ("test_init_array()", BlobTests.test_init_array),
    ("test_init_unsafeRawPointer()", BlobTests.test_init_unsafeRawPointer)
]),
testCase([
    ("test_cursor_to_blob()", StatementTests.test_cursor_to_blob),
    ("test_zero_sized_blob_returns_null()", StatementTests.test_zero_sized_blob_returns_null)
]),
testCase([
    ("test_round_wrapsDoubleExpressionsWithRoundFunction()", CoreFunctionsTests.test_round_wrapsDoubleExpressionsWithRoundFunction),
    ("test_random_generatesExpressionWithRandomFunction()", CoreFunctionsTests.test_random_generatesExpressionWithRandomFunction),
    ("test_length_wrapsStringExpressionWithLengthFunction()", CoreFunctionsTests.test_length_wrapsStringExpressionWithLengthFunction),
    ("test_lowercaseString_wrapsStringExpressionWithLowerFunction()", CoreFunctionsTests.test_lowercaseString_wrapsStringExpressionWithLowerFunction),
    ("test_uppercaseString_wrapsStringExpressionWithUpperFunction()", CoreFunctionsTests.test_uppercaseString_wrapsStringExpressionWithUpperFunction),
    ("test_like_buildsExpressionWithLikeOperator()", CoreFunctionsTests.test_like_buildsExpressionWithLikeOperator),
    ("test_glob_buildsExpressionWithGlobOperator()", CoreFunctionsTests.test_glob_buildsExpressionWithGlobOperator),
    ("test_match_buildsExpressionWithMatchOperator()", CoreFunctionsTests.test_match_buildsExpressionWithMatchOperator),
    ("test_regexp_buildsExpressionWithRegexpOperator()", CoreFunctionsTests.test_regexp_buildsExpressionWithRegexpOperator),
    ("test_collate_buildsExpressionWithCollateOperator()", CoreFunctionsTests.test_collate_buildsExpressionWithCollateOperator),
    ("test_ltrim_wrapsStringWithLtrimFunction()", CoreFunctionsTests.test_ltrim_wrapsStringWithLtrimFunction),
    ("test_ltrim_wrapsStringWithRtrimFunction()", CoreFunctionsTests.test_ltrim_wrapsStringWithRtrimFunction),
    ("test_ltrim_wrapsStringWithTrimFunction()", CoreFunctionsTests.test_ltrim_wrapsStringWithTrimFunction),
    ("test_replace_wrapsStringWithReplaceFunction()", CoreFunctionsTests.test_replace_wrapsStringWithReplaceFunction),
    ("test_substring_wrapsStringWithSubstrFunction()", CoreFunctionsTests.test_substring_wrapsStringWithSubstrFunction),
    ("test_subscriptWithRange_wrapsStringWithSubstrFunction()", CoreFunctionsTests.test_subscriptWithRange_wrapsStringWithSubstrFunction),
    ("test_nilCoalescingOperator_wrapsOptionalsWithIfnullFunction()", CoreFunctionsTests.test_nilCoalescingOperator_wrapsOptionalsWithIfnullFunction),
    ("test_absoluteValue_wrapsNumberWithAbsFucntion()", CoreFunctionsTests.test_absoluteValue_wrapsNumberWithAbsFucntion),
    ("test_contains_buildsExpressionWithInOperator()", CoreFunctionsTests.test_contains_buildsExpressionWithInOperator)
]),
testCase([
    ("testDataFromBlob()", FoundationTests.testDataFromBlob),
    ("testBlobToData()", FoundationTests.testBlobToData)
]),
testCase([
    ("test_init_with_ok_code_returns_nil()", ResultTests.test_init_with_ok_code_returns_nil),
    ("test_init_with_row_code_returns_nil()", ResultTests.test_init_with_row_code_returns_nil),
    ("test_init_with_done_code_returns_nil()", ResultTests.test_init_with_done_code_returns_nil),
    ("test_init_with_other_code_returns_error()", ResultTests.test_init_with_other_code_returns_error),
    ("test_description_contains_error_code()", ResultTests.test_description_contains_error_code),
    ("test_description_contains_statement_and_error_code()", ResultTests.test_description_contains_statement_and_error_code)
]),
testCase([
    ("test_select_withExpression_compilesSelectClause()", QueryTests.test_select_withExpression_compilesSelectClause),
    ("test_select_withStarExpression_compilesSelectClause()", QueryTests.test_select_withStarExpression_compilesSelectClause),
    ("test_select_withNamespacedStarExpression_compilesSelectClause()", QueryTests.test_select_withNamespacedStarExpression_compilesSelectClause),
    ("test_select_withVariadicExpressions_compilesSelectClause()", QueryTests.test_select_withVariadicExpressions_compilesSelectClause),
    ("test_select_withExpressions_compilesSelectClause()", QueryTests.test_select_withExpressions_compilesSelectClause),
    ("test_selectDistinct_withExpression_compilesSelectClause()", QueryTests.test_selectDistinct_withExpression_compilesSelectClause),
    ("test_selectDistinct_withExpressions_compilesSelectClause()", QueryTests.test_selectDistinct_withExpressions_compilesSelectClause),
    ("test_selectDistinct_withStar_compilesSelectClause()", QueryTests.test_selectDistinct_withStar_compilesSelectClause),
    ("test_join_compilesJoinClause()", QueryTests.test_join_compilesJoinClause),
    ("test_join_withExplicitType_compilesJoinClauseWithType()", QueryTests.test_join_withExplicitType_compilesJoinClauseWithType),
    ("test_join_withTableCondition_compilesJoinClauseWithTableCondition()", QueryTests.test_join_withTableCondition_compilesJoinClauseWithTableCondition),
    ("test_join_whenChained_compilesAggregateJoinClause()", QueryTests.test_join_whenChained_compilesAggregateJoinClause),
    ("test_filter_compilesWhereClause()", QueryTests.test_filter_compilesWhereClause),
    ("test_filter_compilesWhereClause_false()", QueryTests.test_filter_compilesWhereClause_false),
    ("test_filter_compilesWhereClause_optional()", QueryTests.test_filter_compilesWhereClause_optional),
    ("test_filter_compilesWhereClause_optional_false()", QueryTests.test_filter_compilesWhereClause_optional_false),
    ("test_where_compilesWhereClause()", QueryTests.test_where_compilesWhereClause),
    ("test_where_compilesWhereClause_false()", QueryTests.test_where_compilesWhereClause_false),
    ("test_where_compilesWhereClause_optional()", QueryTests.test_where_compilesWhereClause_optional),
    ("test_where_compilesWhereClause_optional_false()", QueryTests.test_where_compilesWhereClause_optional_false),
    ("test_filter_whenChained_compilesAggregateWhereClause()", QueryTests.test_filter_whenChained_compilesAggregateWhereClause),
    ("test_group_withSingleExpressionName_compilesGroupClause()", QueryTests.test_group_withSingleExpressionName_compilesGroupClause),
    ("test_group_withVariadicExpressionNames_compilesGroupClause()", QueryTests.test_group_withVariadicExpressionNames_compilesGroupClause),
    ("test_group_withExpressionNameAndHavingBindings_compilesGroupClause()", QueryTests.test_group_withExpressionNameAndHavingBindings_compilesGroupClause),
    ("test_group_withExpressionNamesAndHavingBindings_compilesGroupClause()", QueryTests.test_group_withExpressionNamesAndHavingBindings_compilesGroupClause),
    ("test_order_withSingleExpressionName_compilesOrderClause()", QueryTests.test_order_withSingleExpressionName_compilesOrderClause),
    ("test_order_withVariadicExpressionNames_compilesOrderClause()", QueryTests.test_order_withVariadicExpressionNames_compilesOrderClause),
    ("test_order_withArrayExpressionNames_compilesOrderClause()", QueryTests.test_order_withArrayExpressionNames_compilesOrderClause),
    ("test_order_withExpressionAndSortDirection_compilesOrderClause()", QueryTests.test_order_withExpressionAndSortDirection_compilesOrderClause),
    ("test_order_whenChained_resetsOrderClause()", QueryTests.test_order_whenChained_resetsOrderClause),
    ("test_reverse_withoutOrder_ordersByRowIdDescending()", QueryTests.test_reverse_withoutOrder_ordersByRowIdDescending),
    ("test_reverse_withOrder_reversesOrder()", QueryTests.test_reverse_withOrder_reversesOrder),
    ("test_limit_compilesLimitClause()", QueryTests.test_limit_compilesLimitClause),
    ("test_limit_withOffset_compilesOffsetClause()", QueryTests.test_limit_withOffset_compilesOffsetClause),
    ("test_limit_whenChained_overridesLimit()", QueryTests.test_limit_whenChained_overridesLimit),
    ("test_limit_whenChained_withOffset_overridesOffset()", QueryTests.test_limit_whenChained_withOffset_overridesOffset),
    ("test_alias_aliasesTable()", QueryTests.test_alias_aliasesTable),
    ("test_insert_compilesInsertExpression()", QueryTests.test_insert_compilesInsertExpression),
    ("test_insert_withOnConflict_compilesInsertOrOnConflictExpression()", QueryTests.test_insert_withOnConflict_compilesInsertOrOnConflictExpression),
    ("test_insert_compilesInsertExpressionWithDefaultValues()", QueryTests.test_insert_compilesInsertExpressionWithDefaultValues),
    ("test_insert_withQuery_compilesInsertExpressionWithSelectStatement()", QueryTests.test_insert_withQuery_compilesInsertExpressionWithSelectStatement),
    ("test_update_compilesUpdateExpression()", QueryTests.test_update_compilesUpdateExpression),
    ("test_delete_compilesDeleteExpression()", QueryTests.test_delete_compilesDeleteExpression),
    ("test_delete_compilesExistsExpression()", QueryTests.test_delete_compilesExistsExpression),
    ("test_count_returnsCountExpression()", QueryTests.test_count_returnsCountExpression),
    ("test_scalar_returnsScalarExpression()", QueryTests.test_scalar_returnsScalarExpression),
    ("test_subscript_withExpression_returnsNamespacedExpression()", QueryTests.test_subscript_withExpression_returnsNamespacedExpression),
    ("test_tableNamespacedByDatabase()", QueryTests.test_tableNamespacedByDatabase)
]),
testCase([
    ("test_setterAssignmentOperator_buildsSetter()", SetterTests.test_setterAssignmentOperator_buildsSetter),
    ("test_plusEquals_withStringExpression_buildsSetter()", SetterTests.test_plusEquals_withStringExpression_buildsSetter),
    ("test_plusEquals_withNumberExpression_buildsSetter()", SetterTests.test_plusEquals_withNumberExpression_buildsSetter),
    ("test_minusEquals_withNumberExpression_buildsSetter()", SetterTests.test_minusEquals_withNumberExpression_buildsSetter),
    ("test_timesEquals_withNumberExpression_buildsSetter()", SetterTests.test_timesEquals_withNumberExpression_buildsSetter),
    ("test_dividedByEquals_withNumberExpression_buildsSetter()", SetterTests.test_dividedByEquals_withNumberExpression_buildsSetter),
    ("test_moduloEquals_withIntegerExpression_buildsSetter()", SetterTests.test_moduloEquals_withIntegerExpression_buildsSetter),
    ("test_leftShiftEquals_withIntegerExpression_buildsSetter()", SetterTests.test_leftShiftEquals_withIntegerExpression_buildsSetter),
    ("test_rightShiftEquals_withIntegerExpression_buildsSetter()", SetterTests.test_rightShiftEquals_withIntegerExpression_buildsSetter),
    ("test_bitwiseAndEquals_withIntegerExpression_buildsSetter()", SetterTests.test_bitwiseAndEquals_withIntegerExpression_buildsSetter),
    ("test_bitwiseOrEquals_withIntegerExpression_buildsSetter()", SetterTests.test_bitwiseOrEquals_withIntegerExpression_buildsSetter),
    ("test_bitwiseExclusiveOrEquals_withIntegerExpression_buildsSetter()", SetterTests.test_bitwiseExclusiveOrEquals_withIntegerExpression_buildsSetter),
    ("test_postfixPlus_withIntegerValue_buildsSetter()", SetterTests.test_postfixPlus_withIntegerValue_buildsSetter),
    ("test_postfixMinus_withIntegerValue_buildsSetter()", SetterTests.test_postfixMinus_withIntegerValue_buildsSetter)
])
])

